language: node_js
node_js:
  - "node"

env:
  global:
    - JWT_SECRET=TEST_SECRET 
    - JWT_EXPIRY=1800

sudo: false
cache:
  directories:
  - "$HOME/.npm"

before_install:
  - cd server/
  - npm i -g @nestjs/cli

install: 
  - npm install

jobs:
  - include:
    - stage: test
      script: npm run test
      script: npm run test:e2e

