version: '3'
services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    image: strengdurance/server
    container_name: server
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - server
    image: strengdurance/frontend
    container_name: frontend
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
